---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
    - targetPort: 8080
      port: 80
      nodePort: {{ .Values.ports.nodePort }}
